# -------------------------------------------------------------------------------------
# Hugo Configuration - DonVitsch 专用加强版
# -------------------------------------------------------------------------------------

baseURL = "https://donvitsch.blog/"
title = "DonVitsch's Blog"

# [核心修改] 直接告诉 Hugo 去哪里下载主题
theme = ["github.com/hugo-fixit/FixIt"]

# 语言设置
defaultContentLanguage = "zh-cn"
languageCode = "zh-cn"
languageName = "简体中文"
hasCJKLanguage = true

[module]
  [[module.imports]]
    path = "github.com/hugo-fixit/FixIt"

# 其他功能开启
enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
copyright = "© 2026 DonVitsch"
