baseURL = "https://donvitsch.blog/"
title = "DonVitsch's Blog"
# 换成 Stack 主题的模块路径
theme = "github.com/CaiJimmy/hugo-theme-stack/v3"

defaultContentLanguage = "zh-cn"
languageCode = "zh-cn"

# 基础作者信息
[author]
  name = "DonVitsch"

[params]
  # 侧边栏配置 (Stack 的灵魂)
  [params.sidebar]
    avatar = "avatar.jpg"      # 只要你 static 下有这张图，它必出！
    title = "DonVitsch"
    subtitle = "宝宝不哭喝面条吧 🍜"
    
  # 社交链接 (简单明了)
  [[params.social]]
    name = "GitHub"
    identifier = "github"
    url = "https://github.com/DonVitsch"
    params = { icon = "brand-github" }

# 菜单配置 (顺便帮你把 Archives 改成中文)
[[menu.main]]
  identifier = "archives"
  name = "归档"
  url = "/archives/"
  weight = -1
  params = { icon = "archives" }