baseURL = "https://donvitsch.blog/"
title = "DonVitsch's Blog"
theme = "github.com/hugo-fixit/FixIt"

defaultContentLanguage = "zh-cn"
languageCode = "zh-cn"

# 强制编译所有状态
buildDrafts = true
buildFuture = true

# 作者基本信息
[author]
  name = "DonVitsch"

# 全局参数配置 (合并为一个，确保不报错)
[params]
  themeStyle = "auto"

  # 个人资料页配置
  [params.profile]
    enable = true
    avatarURL = "/avatar.jpg"
    title = "DonVitsch"
    subtitle = "宝宝不哭喝面条吧"
    avatarCircle = true
    social = true
    typeit = true